### ISSUE TITLE
Enhancement Request: Clickable Parries

### ISSUE THREAD

**Issue by TheFabulousIronChef** [mjeffw/saethors-bane-for-dfrpg-public#1]
It would be great if we can enhance the GB Quick Reference Sheet in Foundry (which is quite slick and very visually appealing) by making the "Parry" located in the weapon description clickable just like the attack and the damage for melee weapons, and the Acc bonus and Bulk Penalty for ranged weapons?

At the moment, the "Parry" in the bottom left of the sheet only picks up the first weapon's parry. 

Thanks! Again, this sheet is awesome and is a great way to simplify the standard GCS sheet (which I like, of course) for users.

**Comment by mjeffw** [comment]
Fixed and in the next release -- along with some nice styling changes. And v12 compatibility.
